npclist = [
	'data/npc/acasia-store.groovy',// 杂货店
	'data/npc/ahin.groovy',// 艾琳
	'data/npc/babelquest.groovy',// 危险收集者
	'data/npc/bcn01.groovy',// 杂货店
	'data/npc/bcn02.groovy',// 杂货店
	'data/npc/bcn03.groovy',// 杂货店
	'data/npc/bcn04.groovy',// 杂货店
	'data/npc/bcn05.groovy',// 艾德斯
	'data/npc/bcn06.groovy',// 沃克
	'data/npc/blesscatle-guard.groovy',// 祝福城守卫
	'data/npc/bridge-guard.groovy',// 大桥守卫
	'data/npc/bronzwolverin.groovy',// 铜狼
	'data/npc/clanmaster.groovy',// 公会管理员
	'data/npc/crystal.groovy',// 水晶女孩
	'data/npc/crystalman.groovy',// 水晶男孩
	'data/npc/de-magic.groovy',// 沙漠法师
	'data/npc/de5-civilion1.groovy',// 沙漠难民
	'data/npc/de5-equip.groovy',// 沙漠武器店
	'data/npc/de5-keeper.groovy',// 沙漠守卫
	'data/npc/de5-sdkeeper.groovy',// 吉萨神殿守卫
	'data/npc/de5-store.groovy',// 沙漠杂货店
	'data/npc/derik.groovy',// 二级爵士德克
	'data/npc/desert-guard.groovy',// 沙漠守卫
	'data/npc/donation-box.groovy',// 捐献女孩
	'data/npc/dungeon-keeper.groovy',// 地牢守卫
	'data/npc/flypitcher-store.groovy',// 杂货店
	'data/npc/force-master.groovy',// 力量大师
	'data/npc/fury.groovy',// 狮面魔王
	'data/npc/gold.groovy',// 兑换商店
	'data/npc/goldenwolverin.groovy',// 金狼
	'data/npc/heventgirl.groovy',// 活动女孩
	'data/npc/hosean.groovy',// 豪森安
	'data/npc/hunter.groovy',// 猎人
	'data/npc/itempost.groovy',// 装备发放员
	'data/npc/jin.groovy',// 简
	'data/npc/ji_woo.groovy',// 新手向导
	'data/npc/lake-guard.groovy',// 湖泊守卫
	'data/npc/m_messenger.groovy',// 莉莉丝
	'data/npc/milter.groovy',// 米特尔
	'data/npc/minestone.groovy',// 冰封矿洞杂货店
	'data/npc/mn-013.groovy',// 祝福传送员
	'data/npc/mrcave-keeper.groovy',// 洞穴守卫
	'data/npc/navisko-civilian2.groovy',// 居民米诺
	'data/npc/navisko-dragoman.groovy',// 内维斯克导游
	'data/npc/navisko-equip.groovy',// 铁匠默菲
	'data/npc/navisko-store.groovy',// 杂货店
	'data/npc/navisko-war.groovy',// 仓库管理员
	'data/npc/nevisko-magic.groovy',// 魔法商店
	'data/npc/packjjangpy.groovy',// 幸运的独角兽
	'data/npc/phillay-arad.groovy',// 阿卡达斯
	'data/npc/phillay-civilian1.groovy',// 莫利奶奶
	'data/npc/phillay-civilian2.groovy',// 纽特
	'data/npc/phillay-civilian3.groovy',// 居民
	'data/npc/phillay-dragoman.groovy',// 菲尔拉导游
	'data/npc/phillay-dragoman1.groovy',// 菲尔拉导游
	'data/npc/phillay-equip1.groovy',// 铁匠巴特兹
	'data/npc/phillay-equip2.groovy',// 铁匠德弗里安
	'data/npc/phillay-guard1.groovy',// 菲尔拉守卫
	'data/npc/phillay-guard2.groovy',// 菲尔拉守卫
	'data/npc/phillay-guard3.groovy',// 菲尔拉守卫
	'data/npc/phillay-imbue.groovy',// 神秘的巴云
	'data/npc/phillay-magic.groovy',// 魔法商店
	'data/npc/phillay-master.groovy',// 魔法导师
	'data/npc/phillay-quest.groovy',// 任务商店
	'data/npc/phillay-stone.groovy',// 石头商店
	'data/npc/phillay-store.groovy',// 杂货店
	'data/npc/phillay-warehouse.groovy',// 仓库管理员
	'data/npc/puzzleking.groovy',// 卡片魔兽兵
	'data/npc/ray.groovy',// 魔法师雷蒙
	'data/npc/real_clanmaster.groovy',// 公会管理员
	'data/npc/ricarden-equip1.groovy',// 铁匠古登
	'data/npc/ricarden-equip2.groovy',// 铁匠格斯
	'data/npc/ricarden-guard.groovy',// 里查登守卫
	'data/npc/ricarden-guard1.groovy',// 里查登守卫
	'data/npc/ricarden-guard2.groovy',// 里查登守卫
	'data/npc/ricarden-imbue.groovy',// 合成大师
	'data/npc/ricarden-master.groovy',// 技能导师
	'data/npc/ricarden-quest.groovy',// 任务商店
	'data/npc/ricarden-stone.groovy',// 石头商店
	'data/npc/ricarden-store.groovy',// 杂货店
	'data/npc/ricarden-warehouse.groovy',// 精灵中国仓库管理员
	'data/npc/ruiden-buma.groovy',// 镶嵌布玛熊
	'data/npc/ruiden-civilian1.groovy',// 流浪者罗斯
	'data/npc/ruiden-equip.groovy',// 铁匠鲁加
	'data/npc/ruiden-goblin.groovy',// 打孔魔兽兵
	'data/npc/ruiden-magic.groovy',// 魔法商店
	'data/npc/ruiden-store.groovy',// 杂货店
	'data/npc/salon.groovy',// 萨拉娜
	'data/npc/sillverwolverin.groovy',// 银狼
	'data/npc/skadi.groovy',// 珊蒂
	'data/npc/sod_01.groovy',// 火之精灵卡莎
	'data/npc/sod_02.groovy',// 水之精灵艾丽尔
	'data/npc/sod_03.groovy',// 风之精灵赛尔菲
	'data/npc/sod_04.groovy',// 地之精灵诺雅丝
	'data/npc/sod_05.groovy',// 秘书卡丽纳
	'data/npc/sod_buma.groovy',// SOD布玛熊
	'data/npc/sod_goblin.groovy',// SOD魔兽兵
	'data/npc/stella.groovy',// 佩罗娜
	'data/npc/templer.groovy',// 殿堂法师
	'data/npc/tmcave-keeper.groovy',// 洞穴守卫
	'data/npc/t_messenger.groovy',// 卡迪
	'data/npc/wfzone.groovy',// 传送点发明人
	'data/npc/yura-force-master.groovy',// 力量大师
	'data/npc/yura-guard.groovy',// 幽拉大陆守卫
	'data/npc/yura-guard1.groovy',// 幽拉大陆守卫
	'data/npc/yura-guard2.groovy',// 铁路守卫
	'data/npc/yura-store.groovy',// 杂货店
	'data/npc/yura-warehouse.groovy',// 幽拉仓库管理员
]
